networks:
  ms-net:

services:
  gateway:
    image: nginx:alpine
    container_name: ms-gateway
    ports:
      - "8000:8000"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - customer-service
      - product-service
      - cart-service
      - order-service
    networks:
      - ms-net

  customer-service:
    build:
      context: ./services/customer
    container_name: customer-service
    environment:
      SERVICE_NAME: customer-service
      PORT: "8001"
      DB_DSN: "root:root@tcp(host.docker.internal:3301)/customer_service_db?parseTime=true"
    ports:
      - "8001:8001"
    networks:
      - ms-net

  product-service:
    build:
      context: ./services/product
    container_name: product-service
    environment:
      SERVICE_NAME: product-service
      PORT: "8002"
      DB_DSN: "root:root@tcp(host.docker.internal:3302)/product_service_db?parseTime=true"
    ports:
      - "8002:8002"
    networks:
      - ms-net

  cart-service:
    build:
      context: ./services/cart
    environment:
      SERVICE_NAME: cart-service
      PORT: "8003"
      DB_DSN: "root:root@tcp(host.docker.internal:3303)/cart_service_db?parseTime=true"
      PRODUCT_BASE_URL: "http://product-service:8002"
    expose:
      - "8003"
    networks:
      - ms-net

  cart-lb:
    image: nginx:alpine
    container_name: cart-lb
    ports:
      - "8003:8080"
    volumes:
      - ./gateway/cart.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cart-service
    networks:
      - ms-net

  order-service:
    build:
      context: ./services/order
    environment:
      SERVICE_NAME: order-service
      PORT: "8004"
      DB_DSN: "root:root@tcp(host.docker.internal:3304)/order_service_db?parseTime=true"
      CART_BASE_URL: "http://cart-lb:8080"
      PAYMENT_BASE_URL: "http://payment-lb:8080"
    expose:
      - "8004"
    networks:
      - ms-net


  order-lb:
    image: nginx:alpine
    container_name: order-lb
    ports:
      - "8004:8080"
    volumes:
      - ./gateway/order.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - order-service
    networks:
      - ms-net

  payment-service:
    build:
      context: ./services/payment
    environment:
      SERVICE_NAME: payment-service
      PORT: "8005"
      DB_DSN: "root:root@tcp(host.docker.internal:3305)/payment_service_db?parseTime=true"
    expose:
      - "8005"
    networks:
      - ms-net

  payment-lb:
    image: nginx:alpine
    container_name: payment-lb
    ports:
      - "8005:8080"
    volumes:
      - ./gateway/payment.nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - payment-service
    networks:
      - ms-net

