events {}

http {
  upstream customer { server customer-service:8001; }
  upstream product  { server product-service:8002; }
  upstream cart     { server cart-service:8003; }
  upstream order    { server order-service:8004; }

  server {
    listen 8000;

    location /api/customers/ { proxy_pass http://customer; }
    location /api/customers  { proxy_pass http://customer; }

    location /api/Products/  { proxy_pass http://product; }
    location /api/Products   { proxy_pass http://product; }

    location /api/Carts/     { proxy_pass http://cart; }
    location /api/Carts      { proxy_pass http://cart; }

    location /api/Orders/    { proxy_pass http://order; }
    location /api/Orders     { proxy_pass http://order; }
  }
}
